---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk
    tag: 8u265-jdk

inputs:
  - name: source

outputs:
  - name: build

run:
  path: source/ci/tasks/build-jar.sh
